# Use the official Node.js image with a specific version
FROM node:20.17.0-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if applicable)
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Set environment variables from .env
ENV $(cat .env.production | xargs)

# Expose the port your app will run on
EXPOSE 7001

# Command to run the static file server
CMD ["node", "index.js"]