services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "7001:7001"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
networks:
  web:
    driver: bridge